import { AppError } from '../../common/errors/AppError.js';

const STATUS = {
  APPOINTMENT_NOT_FOUND: 404,
  APPOINTMENT_NOTE_FORBIDDEN: 403,
  NOTE_CLIENT_NOT_ALLOWED: 422,
  NOTE_DATE_NOT_CURRENT: 422,
  NOTE_REQUIRED: 422,
  APPOINTMENT_NOTE_NOT_FOUND: 404,
  INVALID_SERVICE_DATE: 422,
  SERVICE_DATE_OUT_OF_RANGE: 422,
  AUTHORIZATION_NOT_FOUND: 404,
  SERIES_NOT_FOUND: 404,
  ORG_NOT_ACTIVE: 409,
  VERSION_CONFLICT: 409,
  DOUBLE_BOOKING: 409,
  AUTHORIZATION_EXHAUSTED: 409,
  SERIES_ALREADY_CANCELLED: 409,
  INVALID_TIME_RANGE: 422,
  CLIENT_NOT_BOOKABLE: 422,
  CLIENT_NOT_FOUND: 422,
  STAFF_NOT_ELIGIBLE: 422,
  STAFF_NOT_AVAILABLE: 422,
  STAFF_NOT_ASSIGNED: 422,
  AUTHORIZATION_INVALID: 422,
  NO_OCCURRENCES: 422,
  // --- new simple booking pipeline (rebuild) ------------------------------
  BCBA_NOT_ASSIGNED: 422,
  RBT_NOT_ASSIGNED: 422,
  NO_CLINICIAN: 422,
  MULTIPLE_CLINICIANS: 422,
  NO_AUTHORIZATION: 422,
  APPOINTMENT_DATE_IN_PAST: 422,
  APPOINTMENT_DATE_OUTSIDE_CURRENT_MONTH: 422,
  UNITS_INVALID: 422,
  END_BEFORE_START: 422,
  TENANT_CONTEXT_MISSING: 500,
};
const DEFAULT = {
  APPOINTMENT_NOT_FOUND: 'Appointment not found',
  APPOINTMENT_NOTE_FORBIDDEN: 'You don\u2019t have access to notes for this appointment.',
  NOTE_CLIENT_NOT_ALLOWED: 'Choose one of your assigned clients for this note.',
  NOTE_DATE_NOT_CURRENT: 'Appointment notes can only be written for the current business date. Refresh and try again.',
  NOTE_REQUIRED: 'Enter the note before saving.',
  APPOINTMENT_NOTE_NOT_FOUND: 'There is no appointment note for the current business date.',
  INVALID_SERVICE_DATE: 'Choose a valid appointment date for this note.',
  SERVICE_DATE_OUT_OF_RANGE: 'That date isn\u2019t part of this appointment\u2019s schedule.',
  AUTHORIZATION_NOT_FOUND: 'Authorization not found',
  ORG_NOT_ACTIVE: 'Scheduling is only available while the organization is active.',
  VERSION_CONFLICT: 'This appointment changed since you loaded it. Reload and try again.',
  DOUBLE_BOOKING: 'That time overlaps an existing appointment for the staff member or client.',
  AUTHORIZATION_EXHAUSTED: 'The authorization does not have enough units remaining.',
  INVALID_TIME_RANGE: 'The appointment must start before it ends and not span more than one day.',
  CLIENT_NOT_BOOKABLE: 'This client cannot be scheduled in their current status.',
  STAFF_NOT_ELIGIBLE: 'The staff member is not active or has no valid credential.',
  STAFF_NOT_AVAILABLE: 'The staff member is not available at that time.',
  STAFF_NOT_ASSIGNED: 'The staff member is not assigned to this child at that time.',
  AUTHORIZATION_INVALID: 'The authorization is not valid for this client, service, or date.',
  CLIENT_NOT_FOUND: 'Select a valid client for your company before booking.',
  BCBA_NOT_ASSIGNED: 'Please assign a BCBA to this client before continuing.',
  RBT_NOT_ASSIGNED: 'Please assign an RBT to this client before continuing.',
  NO_CLINICIAN: 'Assign one clinician — either a BCBA or an RBT — before booking.',
  MULTIPLE_CLINICIANS: 'An appointment is for one clinician only. Choose a BCBA or an RBT — not both. To schedule both for this child, create two separate appointments.',
  NO_AUTHORIZATION: 'No ABA or FBA authorization found for this client. Please create an authorization before continuing.',
  UNITS_INVALID: 'Units are required and must be a number greater than 0.',
  END_BEFORE_START: 'End date/time must be on or after the start date/time.',
  APPOINTMENT_DATE_IN_PAST: 'Appointments can\u2019t be scheduled for a past date. Choose today or a later date this month.',
  APPOINTMENT_DATE_OUTSIDE_CURRENT_MONTH: 'Appointments can only be scheduled within the current month.',
  SERIES_NOT_FOUND: 'Recurring series not found',
  SERIES_ALREADY_CANCELLED: 'This series is already cancelled.',
  NO_OCCURRENCES: 'The recurrence rule produced no occurrences.',
  TENANT_CONTEXT_MISSING: 'Tenant context missing',
};
export function schedulingError(code, { message, context, details } = {}) {
  return new AppError(code, {
    status: STATUS[code] ?? 400,
    message: message ?? DEFAULT[code] ?? code,
    ...(context ? { context } : {}),
    ...(details ? { details } : {}),
  });
}
