/**
 * Platform-locked role → permission templates. Code, not data: a tenant cannot
 * grant its receptionist the owner's export capability by editing a row.
 * Ported verbatim from the original RBAC engine. The eight system roles below
 * match the per-tenant seed (owner, org_admin, bcba, rbt, billing_staff,
 * scheduler, payroll_staff, receptionist).
 */
export const SYSTEM_ROLE_TEMPLATES = Object.freeze({
  owner: [
    { key: 'clients.verify_insurance', scope: 'ORGANIZATION' },
    { key: 'reconciliation.read', scope: 'ORGANIZATION' },
    { key: 'reconciliation.manage', scope: 'ORGANIZATION' },
    { key: 'finance.reports.read', scope: 'ORGANIZATION' },
    { key: 'finance.export', scope: 'ORGANIZATION' },
    { key: 'claims.read', scope: 'ORGANIZATION' },
    { key: 'claims.manage', scope: 'ORGANIZATION' },
    { key: 'era.read', scope: 'ORGANIZATION' },
    { key: 'era.resolve', scope: 'ORGANIZATION' },
    { key: 'timesheets.read', scope: 'ORGANIZATION' },
    { key: 'timesheets.write', scope: 'ORGANIZATION' },
    { key: 'timesheets.approve', scope: 'ORGANIZATION' },
    { key: 'payroll.read', scope: 'ORGANIZATION' },
    { key: 'payroll.manage', scope: 'ORGANIZATION' },
    { key: 'billing.read', scope: 'ORGANIZATION' },
    { key: 'billing.manage', scope: 'ORGANIZATION' },
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'ORGANIZATION' },
    { key: 'plans.create', scope: 'ORGANIZATION' },
    { key: 'plans.update', scope: 'ORGANIZATION' },
    { key: 'plans.archive', scope: 'ORGANIZATION' },
    { key: 'sessions.read', scope: 'ORGANIZATION' },
    { key: 'sessions.write', scope: 'ORGANIZATION' },
    { key: 'sessions.freeze', scope: 'ORGANIZATION' },
    { key: 'documents.read', scope: 'ORGANIZATION' },
    { key: 'documents.write', scope: 'ORGANIZATION' },
    { key: 'documents.finalize', scope: 'ORGANIZATION' },
    { key: 'dashboards.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.write', scope: 'ORGANIZATION' },
    { key: 'scheduling.manage', scope: 'ORGANIZATION' },
    { key: 'staff.read', scope: 'ORGANIZATION' },
    { key: 'staff.manage', scope: 'ORGANIZATION' },
    { key: 'supervision.log', scope: 'ORGANIZATION' },
    { key: 'supervision.signoff', scope: 'ORGANIZATION' },
    { key: 'credentials.read', scope: 'ORGANIZATION' },
    { key: 'credentials.manage', scope: 'ORGANIZATION' },
    { key: 'clients.read', scope: 'ORGANIZATION' },
    { key: 'clients.create', scope: 'ORGANIZATION' },
    { key: 'clients.update', scope: 'ORGANIZATION' },
    { key: 'clients.care_team.manage', scope: 'ORGANIZATION' },
    { key: 'clients.medical.manage', scope: 'ORGANIZATION' },
    { key: 'clients.archive', scope: 'ORGANIZATION' },
    { key: 'organization.update', scope: 'ORGANIZATION' },
    { key: 'organization.offboard_request', scope: 'ORGANIZATION' },
    { key: 'organization.export', scope: 'ORGANIZATION' },
    { key: 'organization.usage.read', scope: 'ORGANIZATION' },
    { key: 'audit.read', scope: 'ORGANIZATION' },
    { key: 'users.read', scope: 'ORGANIZATION' },
    { key: 'users.invite', scope: 'ORGANIZATION' },
    { key: 'users.manage', scope: 'ORGANIZATION' },
    { key: 'users.role.assign', scope: 'ORGANIZATION' },
    { key: 'roles.read', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'ORGANIZATION' },
  ],
  org_admin: [
    { key: 'clients.verify_insurance', scope: 'ORGANIZATION' },
    { key: 'reconciliation.read', scope: 'ORGANIZATION' },
    { key: 'reconciliation.manage', scope: 'ORGANIZATION' },
    { key: 'finance.reports.read', scope: 'ORGANIZATION' },
    { key: 'finance.export', scope: 'ORGANIZATION' },
    { key: 'claims.read', scope: 'ORGANIZATION' },
    { key: 'claims.manage', scope: 'ORGANIZATION' },
    { key: 'era.read', scope: 'ORGANIZATION' },
    { key: 'era.resolve', scope: 'ORGANIZATION' },
    { key: 'timesheets.read', scope: 'ORGANIZATION' },
    { key: 'timesheets.write', scope: 'ORGANIZATION' },
    { key: 'timesheets.approve', scope: 'ORGANIZATION' },
    { key: 'payroll.read', scope: 'ORGANIZATION' },
    { key: 'payroll.manage', scope: 'ORGANIZATION' },
    { key: 'billing.read', scope: 'ORGANIZATION' },
    { key: 'billing.manage', scope: 'ORGANIZATION' },
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'ORGANIZATION' },
    { key: 'plans.create', scope: 'ORGANIZATION' },
    { key: 'plans.update', scope: 'ORGANIZATION' },
    { key: 'plans.archive', scope: 'ORGANIZATION' },
    { key: 'sessions.read', scope: 'ORGANIZATION' },
    { key: 'sessions.write', scope: 'ORGANIZATION' },
    { key: 'sessions.freeze', scope: 'ORGANIZATION' },
    { key: 'documents.read', scope: 'ORGANIZATION' },
    { key: 'documents.write', scope: 'ORGANIZATION' },
    { key: 'documents.finalize', scope: 'ORGANIZATION' },
    { key: 'dashboards.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.write', scope: 'ORGANIZATION' },
    { key: 'scheduling.manage', scope: 'ORGANIZATION' },
    { key: 'staff.read', scope: 'ORGANIZATION' },
    { key: 'staff.manage', scope: 'ORGANIZATION' },
    { key: 'supervision.log', scope: 'ORGANIZATION' },
    { key: 'supervision.signoff', scope: 'ORGANIZATION' },
    { key: 'credentials.read', scope: 'ORGANIZATION' },
    { key: 'credentials.manage', scope: 'ORGANIZATION' },
    { key: 'clients.read', scope: 'ORGANIZATION' },
    { key: 'clients.create', scope: 'ORGANIZATION' },
    { key: 'clients.update', scope: 'ORGANIZATION' },
    { key: 'clients.care_team.manage', scope: 'ORGANIZATION' },
    { key: 'clients.medical.manage', scope: 'ORGANIZATION' },
    { key: 'clients.archive', scope: 'ORGANIZATION' },
    { key: 'organization.update', scope: 'ORGANIZATION' },
    { key: 'users.read', scope: 'ORGANIZATION' },
    { key: 'users.invite', scope: 'ORGANIZATION' },
    { key: 'users.manage', scope: 'ORGANIZATION' },
    { key: 'users.role.assign', scope: 'ORGANIZATION' },
    { key: 'roles.read', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'ORGANIZATION' },
    { key: 'audit.read', scope: 'ORGANIZATION' },
  ],
  bcba: [
    { key: 'timesheets.read', scope: 'SELF' },
    { key: 'timesheets.write', scope: 'SELF' },
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'TEAM' },
    { key: 'plans.create', scope: 'TEAM' },
    { key: 'plans.update', scope: 'TEAM' },
    { key: 'plans.archive', scope: 'TEAM' },
    { key: 'sessions.read', scope: 'TEAM' },
    { key: 'sessions.write', scope: 'TEAM' },
    { key: 'sessions.freeze', scope: 'TEAM' },
    { key: 'documents.read', scope: 'TEAM' },
    { key: 'documents.write', scope: 'TEAM' },
    { key: 'documents.finalize', scope: 'TEAM' },
    { key: 'dashboards.read', scope: 'TEAM' },
    // Scheduling is VIEW-ONLY for clinicians. Company/Admin (owner, org_admin,
    // scheduler, receptionist) is the scheduling authority; a BCBA sees their
    // caseload's calendar but cannot create/modify appointments — a direct
    // POST /scheduling/appointments is rejected (no scheduling.write). This
    // mirrors the RBT grant, which was already read-only.
    { key: 'scheduling.read', scope: 'TEAM' },
    { key: 'staff.read', scope: 'TEAM' },
    { key: 'supervision.log', scope: 'TEAM' },
    { key: 'supervision.signoff', scope: 'TEAM' },
    { key: 'credentials.read', scope: 'TEAM' },
    { key: 'clients.read', scope: 'TEAM' },
    // NOTE: a BCBA deliberately has NO clients.update. Child administration —
    // demographics (PATCH /clients/:id, i.e. the Company child editor), medical,
    // guardians, contacts, insurance, intake, service authorizations — is
    // Company/Admin-only. The BCBA's clinical work runs on plans.*, sessions.*
    // and documents.* (above), so this restriction does not touch treatment
    // plans, goals, programs, targets or weekly plans. Blueprint: "Only Company
    // child administration must remain restricted."
    { key: 'users.read', scope: 'TEAM' },
    { key: 'roles.read', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'SELF' },
  ],
  rbt: [
    { key: 'timesheets.read', scope: 'SELF' },
    { key: 'timesheets.write', scope: 'SELF' },
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'SELF' },
    { key: 'sessions.read', scope: 'SELF' },
    { key: 'sessions.write', scope: 'SELF' },
    { key: 'documents.read', scope: 'SELF' },
    { key: 'documents.write', scope: 'SELF' },
    { key: 'dashboards.read', scope: 'SELF' },
    { key: 'scheduling.read', scope: 'SELF' },
    { key: 'staff.read', scope: 'SELF' },
    { key: 'clients.read', scope: 'SELF' },
    { key: 'permissions.read', scope: 'SELF' },
  ],
  billing_staff: [
    { key: 'clients.verify_insurance', scope: 'ORGANIZATION' },
    { key: 'reconciliation.read', scope: 'ORGANIZATION' },
    { key: 'reconciliation.manage', scope: 'ORGANIZATION' },
    { key: 'finance.reports.read', scope: 'ORGANIZATION' },
    { key: 'finance.export', scope: 'ORGANIZATION' },
    { key: 'claims.read', scope: 'ORGANIZATION' },
    { key: 'claims.write', scope: 'ORGANIZATION' },
    { key: 'claims.submit', scope: 'ORGANIZATION' },
    { key: 'claims.manage', scope: 'ORGANIZATION' },
    { key: 'era.read', scope: 'ORGANIZATION' },
    { key: 'era.process', scope: 'ORGANIZATION' },
    { key: 'era.resolve', scope: 'ORGANIZATION' },
    { key: 'billing.read', scope: 'ORGANIZATION' },
    { key: 'billing.manage', scope: 'ORGANIZATION' },
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'ORGANIZATION' },
    { key: 'sessions.read', scope: 'ORGANIZATION' },
    { key: 'documents.read', scope: 'ORGANIZATION' },
    { key: 'dashboards.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.read', scope: 'ORGANIZATION' },
    { key: 'staff.read', scope: 'ORGANIZATION' },
    { key: 'clients.read', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'SELF' },
  ],
  scheduler: [
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'ORGANIZATION' },
    { key: 'sessions.read', scope: 'ORGANIZATION' },
    { key: 'documents.read', scope: 'ORGANIZATION' },
    { key: 'dashboards.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.write', scope: 'ORGANIZATION' },
    { key: 'scheduling.manage', scope: 'ORGANIZATION' },
    { key: 'staff.read', scope: 'ORGANIZATION' },
    { key: 'clients.read', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'SELF' },
  ],
  payroll_staff: [
    { key: 'timesheets.read', scope: 'ORGANIZATION' },
    { key: 'timesheets.write', scope: 'ORGANIZATION' },
    { key: 'timesheets.approve', scope: 'ORGANIZATION' },
    { key: 'payroll.read', scope: 'ORGANIZATION' },
    { key: 'payroll.manage', scope: 'ORGANIZATION' },
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'ORGANIZATION' },
    { key: 'sessions.read', scope: 'ORGANIZATION' },
    { key: 'documents.read', scope: 'ORGANIZATION' },
    { key: 'dashboards.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.read', scope: 'ORGANIZATION' },
    { key: 'staff.read', scope: 'ORGANIZATION' },
    { key: 'clients.read', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'SELF' },
  ],
  receptionist: [
    { key: 'organization.read', scope: 'ORGANIZATION' },
    { key: 'plans.read', scope: 'ORGANIZATION' },
    { key: 'sessions.read', scope: 'ORGANIZATION' },
    { key: 'documents.read', scope: 'ORGANIZATION' },
    { key: 'documents.write', scope: 'ORGANIZATION' },
    { key: 'dashboards.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.read', scope: 'ORGANIZATION' },
    { key: 'scheduling.write', scope: 'ORGANIZATION' },
    { key: 'staff.read', scope: 'ORGANIZATION' },
    { key: 'clients.read', scope: 'ORGANIZATION' },
    { key: 'clients.create', scope: 'ORGANIZATION' },
    { key: 'clients.update', scope: 'ORGANIZATION' },
    { key: 'permissions.read', scope: 'SELF' },
  ],
});

export const SYSTEM_ROLE_KEYS = Object.freeze(Object.keys(SYSTEM_ROLE_TEMPLATES));

export const PLATFORM_OPERATOR_GRANTS = Object.freeze([
  { key: 'platform.tenant.create', scope: 'PLATFORM' },
  { key: 'platform.tenant.read', scope: 'PLATFORM' },
  { key: 'platform.tenant.transition', scope: 'PLATFORM' },
  { key: 'platform.tenant.provision', scope: 'PLATFORM' },
  { key: 'platform.tenant.agreement', scope: 'PLATFORM' },
  { key: 'platform.tenant.offboard', scope: 'PLATFORM' },
  { key: 'platform.tenant.destroy_approve', scope: 'PLATFORM' },
  { key: 'platform.tenant.invite_owner', scope: 'PLATFORM' },
]);
