import { AppError } from '../../common/errors/AppError.js';

/** Error codes for the clients module. */
const STATUS = {
  CLIENT_NOT_FOUND: 404,
  GUARDIAN_NOT_FOUND: 404,
  CONTACT_NOT_FOUND: 404,
  MEDICAL_ENTRY_NOT_FOUND: 404,
  MEDICAL_ATTACHMENT_INVALID: 422,
  ASSIGNMENT_NOT_FOUND: 404,
  STAFF_NOT_FOUND: 404,
  STAFF_INACTIVE: 409,
  ASSIGNMENT_EXISTS: 409,
  ORG_NOT_ACTIVE: 409,
  INTAKE_TRANSITION_INVALID: 422,
  GUARDIAN_EMAIL_UNAVAILABLE: 422,
  EMAIL_UNSUPPORTED_VARIABLE: 422,
  EMAIL_TEMPLATE_NOT_FOUND: 404,
  EMAIL_TEMPLATE_NAME_EXISTS: 409,
  COMMUNICATION_UNAVAILABLE: 503,
  CARE_TEAM_NO_RECIPIENTS: 422,
  CARE_TEAM_EMPTY: 422,
  ASSIGNMENT_RATE_INVALID: 422,
  ASSIGNMENT_HOURS_INVALID: 422,
  ASSIGNMENT_ROLE_INELIGIBLE: 422,
  ASSIGNMENT_OVER_CAPACITY: 422,
  CLIENT_ALREADY_HAS_RBT: 409,
  CLIENT_ALREADY_HAS_BCBA: 409,
  ASSIGNMENT_DATES_INVALID: 422,
  AUTHORIZATION_DENY_REASON_REQUIRED: 422,
  AUTHORIZATION_TRANSITION_INVALID: 422,
  AUTHORIZATION_DATES_INVALID: 422,
  AUTHORIZATION_EXISTS: 409,
  AUTHORIZATION_NOT_FOUND: 404,
  VERSION_CONFLICT: 409,
  CLIENT_NUMBER_EXHAUSTED: 409,
  CLIENT_ACTIVATION_REQUIRES_PARENT: 422,
  PARENT_DETAILS_REQUIRED: 422,
  TENANT_CONTEXT_MISSING: 500,
};
const DEFAULT = {
  CLIENT_NOT_FOUND: 'Client not found',
  GUARDIAN_NOT_FOUND: 'Guardian not found',
  CONTACT_NOT_FOUND: 'Contact not found',
  MEDICAL_ENTRY_NOT_FOUND: 'Medical entry not found',
  MEDICAL_ATTACHMENT_INVALID: 'One or more attachments are not valid documents for this child',
  ASSIGNMENT_NOT_FOUND: 'Care-team assignment not found',
  STAFF_NOT_FOUND: 'Staff member not found',
  STAFF_INACTIVE: 'That staff member is not active and cannot be assigned.',
  ASSIGNMENT_EXISTS: 'That staff member already holds that role for this client.',
  ORG_NOT_ACTIVE: 'Clinical records can only be created while the organization is active.',
  INTAKE_TRANSITION_INVALID: 'That intake status change is not allowed from the current state.',
  GUARDIAN_EMAIL_UNAVAILABLE: 'Guardian email address is not available for this child.',
  EMAIL_UNSUPPORTED_VARIABLE: 'The message uses variables that are not allowed.',
  EMAIL_TEMPLATE_NOT_FOUND: 'That email template does not exist.',
  EMAIL_TEMPLATE_NAME_EXISTS: 'A template with this name already exists. Choose a different name.',
  COMMUNICATION_UNAVAILABLE: 'Messaging is temporarily unavailable.',
  CARE_TEAM_NO_RECIPIENTS: 'None of the selected recipients are on this child’s active care team.',
  CARE_TEAM_EMPTY: 'This child has no active care-team members to message.',
  ASSIGNMENT_RATE_INVALID: 'The hourly pay rate must be zero or greater.',
  ASSIGNMENT_HOURS_INVALID: 'Weekly assigned hours must be between 0 and 168.',
  ASSIGNMENT_ROLE_INELIGIBLE: 'That staff member’s discipline does not match the selected role.',
  ASSIGNMENT_OVER_CAPACITY: 'This would exceed the child’s approved weekly hours.',
  CLIENT_ALREADY_HAS_RBT: 'This child already has an active RBT. End the current RBT assignment before assigning a new one.',
  CLIENT_ALREADY_HAS_BCBA: 'This child already has an active BCBA. End the current BCBA assignment before assigning a new one.',
  ASSIGNMENT_DATES_INVALID: 'The end date must be on or after the start date.',
  AUTHORIZATION_DENY_REASON_REQUIRED: 'A reason is required to deny an authorization.',
  AUTHORIZATION_TRANSITION_INVALID: 'That authorization status change is not allowed from the current state.',
  AUTHORIZATION_DATES_INVALID: 'The end date must be on or after the start date.',
  AUTHORIZATION_EXISTS: 'An authorization with this number already exists for this child. Use a different authorization number.',
  AUTHORIZATION_NOT_FOUND: 'Authorization not found',
  VERSION_CONFLICT: 'This record changed since you loaded it. Reload and try again.',
  CLIENT_NUMBER_EXHAUSTED: 'Could not allocate a unique client number. Please retry.',
  CLIENT_ACTIVATION_REQUIRES_PARENT: 'Add at least one parent before activating this client.',
  PARENT_DETAILS_REQUIRED: 'Please add the parent or guardian details before continuing.',
  TENANT_CONTEXT_MISSING: 'Tenant context missing',
};
export function clientsError(code, { message, context, details } = {}) {
  return new AppError(code, {
    status: STATUS[code] ?? 400,
    message: message ?? DEFAULT[code] ?? code,
    ...(context ? { context } : {}),
    ...(details ? { details } : {}),
  });
}
